apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "davmail.fullname" . }}-pvc
spec:
  accessModes: {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
